# Generated by Django 5.1 on 2024-08-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id_fornecedor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('cnpj', models.IntegerField()),
                ('endereco', models.TextField(max_length=500)),
                ('email', models.TextField(max_length=255)),
                ('produto', models.TextField(max_length=255)),
            ],
        ),
    ]
