# Generated by Django 5.1 on 2024-08-26 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro_fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fornecedores',
            new_name='Fornecedor',
        ),
    ]
